name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version if needed

      - name: Build the site
        run: npm install && npm run build  # Modify this if you're not using npm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Path to your build output directory (e.g., ./dist)
